#!/bin/bash
#
# tervitusskript
#
# skripti algus
#
echo -n "Tere " 
echo -n `who am i | cut -c1 | tr [:lower:] [:upper:]` #lõika esimene täht ja muuda suureks
echo -n `who am i | cut -c2- | cut -f1 -d" " ` # lõika kõik tähed alates 2-st
echo -n "!"
#
# skripti lõpp
